import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import getCurrentUser from './actions/getCurrentUser';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });
const KAKAO_SDK_URL = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_MAP_API_KEY}&autoload=false`;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang='ko'>
      <body className={inter.className}>
        <Navbar currentUser={currentUser} />
        <div>{children}</div>
        <Script src={KAKAO_SDK_URL} />
      </body>
    </html>
  );
}
